---

# -------------------------------------------------
# Default Variables
# -------------------------------------------------
 
setup_workshop_username: "{{ student_name }}"
setup_workshop_groupname: users
setup_workshop_username_home: "/home/{{ student_name }}"
setup_workshop_repository: https://github.com/rhpds/automating-ripu-with-ansible-showroom
setup_workshop_repository_version: main
setup_workshop_exercise_src_dir: content/modules/ROOT
setup_workshop_exercise_dest_dir: ipu-workshop
workshop_type: ripu
