---

- name: Copy motd template
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd

- name: Copy setup.yml playbook
  ansible.builtin.copy:
    src: setup.yml
    dest: "{{ setup_workshop_username_home }}/setup.yml"
    owner: "{{ setup_workshop_username }}"
    group: "{{ setup_workshop_groupname }}"

- name: Clone rhel-workshop
  ansible.builtin.git:
    repo: "{{ setup_workshop_repository }}"
    dest: /tmp/workshops
    version: "{{ setup_workshop_repository_version }}"

- name: Copy rhel-workshop to users home
  ansible.builtin.copy:
    src: "/tmp/workshops/{{ setup_workshop_exercise_src_dir }}/"
    dest: "{{ setup_workshop_username_home }}/{{ setup_workshop_exercise_dest_dir }}/"
    remote_src: true
    owner: "{{ setup_workshop_username }}"
    group: "{{ setup_workshop_groupname }}"
    mode: '0755'

- name: Clean workshop clone directory
  ansible.builtin.file:
    path: "/tmp/workshops"
    state: absent
...
